# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-DirWatch
version:      0.02
version_from: DirWatch.pm
installdirs:  site
requires:
    POE:                           0.12
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.26
