--- 
abstract: Directory Watcher for POE
author: 
  - Guillermo Roditi, <groditi@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Component-DirWatch
no_index: 
  directory: 
    - inc
    - t
requires: 
  File::Signature: 0
  Moose: 0.24
  MooseX::Types::Path::Class: 0
  POE: 0.12
  Path::Class: 0
  Time::HiRes: 0
version: 0.100000_01
